stages:
  - lint
  - depends
  - build
  - staple
  - installer
  - package

.depends:
  stage: depends
  script:
    - tools/builddeps.sh

.build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - $PREFIX/bin/qt-cmake -DGREEN_ENV=$([[ $CI_COMMIT_REF_NAME = release_* ]] && echo "Production" || echo "Testing") -DGREEN_BUILD_ID=$([[ $CI_COMMIT_REF_NAME = release_* ]] && echo "" || echo "$CI_COMMIT_SHORT_SHA") -DGREEN_LOG_FILE=$CI_COMMIT_BRANCH .
    - make -j

include:
  - local: 'ci/lint.yml'
  - local: 'ci/linux-x86_64.yml'
  - local: 'ci/windows-x86_64.yml'
  - local: 'ci/macos-arm64.yml'
  - local: 'ci/macos-x86_64.yml'
  - local: 'ci/macos-universal.yml'
  - local: 'ci/package.yml'
