stages:
  - lint
  - depends
  - build
  - staple

.depends:
  stage: depends
  script:
    - tools/builddeps.sh

.build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - $PREFIX/bin/qt-cmake -DGREEN_ENV=Testing -DGREEN_BUILD_ID=-$CI_COMMIT_SHORT_SHA .
    - make -j

include:
  - local: 'ci/*.yml'
