stages:
  - lint
  - depends
  - build

.depends:
  stage: depends
  script:
    - tools/builddeps.sh

.build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - depends/bin/qt-cmake .
    - make -j

include:
  - local: 'ci/*.yml'
