image: greenaddress/ci@sha256:42cddc47f97e66cd6575931cbf4f8635ecc2cbb9fc7c1ec1468a5dcfda1198d0

stages:
  - build
  - signartifacts
  - deploy

bionic_release:
  tags:
    - ga
  stage: build
  script:
    - ./tools/buildgreen.sh linux
    - mkdir build-linux-gcc
    - cp /docker_bld_root/*/green build-linux-gcc/
    - cp /docker_bld_root/*/BlockstreamGreen-x86_64.AppImage build-linux-gcc/
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    when: always
    paths:
    - build-linux-gcc/green
    - build-linux-gcc/BlockstreamGreen-x86_64.AppImage

windows_release:
  tags:
    - ga
  stage: build
  script:
    - ./tools/buildgreen.sh windows
    - mkdir -p build-mingw-w64/release
    - cp /docker_bld_root/*/release/green.exe "build-mingw-w64/release/Green.exe"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    when: always
    paths:
    - build-mingw-w64/release/Green.exe

osx_release:
  tags:
    - osx
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/buildgreen.sh osx
  cache:
    key: build-cache-osx
    paths:
    - build-osx-clang/gdk-*/gdk.h
    - build-osx-clang/gdk-*/build.done
    - build-osx-clang/gdk-*/libgreenaddress_full.a
    - build-osx-clang/qt-release*
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    when: always
    paths:
    - build-osx-clang/green.app

bionic_allsymbolsunstripped_manual:
  extends: bionic_release
  stage: build
  when: manual
  script:
    - ./tools/bionic_deps.sh
    - ./tools/buildgreen.sh linux allsymbolsunstripped

osx_allsymbolsunstripped_manual:
  extends: osx_release
  stage: build
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/buildgreen.sh osx allsymbolsunstripped

windows_allsymbolsunstripped_manual:
  extends: windows_release
  stage: build
  when: manual
  script:
    - ./tools/bionic_deps.sh
    - ./tools/buildgreen.sh windows allsymbolsunstripped

osx_sign:
  tags:
    - osxsigner
  only:
    - /^release_.*/
  stage: signartifacts
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    when: always
    paths:
    - build-osx-clang/green.app
  needs:
    - osx_release
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/osxsign.sh
    - cd build-osx-clang
    - ../tools/osxstaple.sh

windows_sign:
  tags:
    - garelease
  only:
    - /^release_.*/
  stage: signartifacts
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    when: always
    paths:
    - build-mingw-w64/release/GreenSigned.exe
  needs:
    - windows_release
  script:
    - cd $CI_PROJECT_DIR/build-mingw-w64/release
    - /opt/process_release_windows

package_release:
  tags:
    - garelease
  only:
    - /^release_.*/
  stage: deploy
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/green_qt_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - rm -fr green_qt_dist
    - mkdir green_qt_dist
    - mv build-mingw-w64/release/GreenSigned.exe "Blockstream Green.exe"
    - zip -j green_qt_dist/BlockstreamGreen_Windows_x86_64.zip "Blockstream Green.exe"
    - rm -rf "build-osx-clang/Blockstream Green.app"
    - mv build-osx-clang/green.app "build-osx-clang/Blockstream Green.app"
    - (cd build-osx-clang; zip -r ../green_qt_dist/BlockstreamGreen_MacOS_x86_64.zip "Blockstream Green.app")
    - chmod +x build-linux-gcc/green
    - tar czf green_qt_dist/BlockstreamGreen_Linux_x86_64.tar.gz -C build-linux-gcc green
    - cp build-linux-gcc/BlockstreamGreen-x86_64.AppImage green_qt_dist
    - chmod +x green_qt_dist/BlockstreamGreen-x86_64.AppImage
    - cd green_qt_dist
    - /opt/process_release
  needs:
    - bionic_release
    - osx_sign
    - windows_sign
