image: greenaddress/ci@sha256:a1369e0a93d521c49eeb9d8f2b8013ac63ed4d5bc7a026cbacc77ac717408e75

stages:
  - build
  - signartifacts
  - deploy

bionic_release:
  tags:
    - ga
  stage: build
  script:
    - ./tools/buildgreen.sh linux
    - mkdir build-linux-gcc
    - cp /docker_bld_root/*/Green build-linux-gcc/
    - cp /docker_bld_root/*/Green-x86_64.AppImage build-linux-gcc/
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-linux-gcc/Green
    - build-linux-gcc/Green-x86_64.AppImage

windows_release:
  tags:
    - ga
  stage: build
  script:
    - ./tools/buildgreen.sh windows
    - mkdir -p build-mingw-w64/release
    - cp /docker_bld_root/*/release/Green.exe build-mingw-w64/release/
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-mingw-w64/release/Green.exe

osx_release:
  tags:
    - osx
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/buildgreen.sh osx
  cache:
    key: build-cache-osx
    paths:
    - build-osx-clang/gdk-*/gdk.h
    - build-osx-clang/gdk-*/build.done
    - build-osx-clang/gdk-*/libgreenaddress_full.a
    - build-osx-clang/qt-release*
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-osx-clang/Green.app

bionic_allsymbolsunstripped_manual:
  extends: bionic_release
  stage: build
  when: manual
  script:
    - ./tools/bionic_deps.sh
    - ./tools/buildgreen.sh linux allsymbolsunstripped

osx_allsymbolsunstripped_manual:
  extends: osx_release
  stage: build
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/buildgreen.sh osx allsymbolsunstripped

windows_allsymbolsunstripped_manual:
  extends: windows_release
  stage: build
  when: manual
  script:
    - ./tools/bionic_deps.sh
    - ./tools/buildgreen.sh windows allsymbolsunstripped

osx_sign:
  tags:
    - osxsigner
  only:
    - /^release_.*/
  stage: signartifacts
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-osx-clang/GreenQt_MacOSX_x86_64.zip
  needs:
    - osx_release
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/osxsign.sh
    - cd build-osx-clang
    - ../tools/osxstaple.sh

windows_sign:
  tags:
    - garelease
  only:
    - /^release_.*/
  stage: signartifacts
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-mingw-w64/release/GreenSigned.exe
  needs:
    - windows_release
  script:
    - cd $CI_PROJECT_DIR/build-mingw-w64/release
    - /opt/process_release_windows

package_release:
  tags:
    - garelease
  only:
    - /^release_.*/
  stage: deploy
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/green_qt_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - rm -fr green_qt_dist
    - mkdir green_qt_dist
    - mv build-mingw-w64/release/GreenSigned.exe Green.exe
    - zip -j green_qt_dist/GreenQt_Windows_x86_64.zip Green.exe
    - (cd build-osx-clang; mv GreenQt_MacOSX_x86_64.zip ../green_qt_dist)
    - chmod +x build-linux-gcc/Green
    - tar czf green_qt_dist/GreenQt_Linux_x86_64.tar.gz -C build-linux-gcc Green
    - tar czf green_qt_dist/GreenQt_AppImage_x86_64.tar.gz -C build-linux-gcc Green-x86_64.AppImage
    - cd green_qt_dist
    - /opt/process_release
  needs:
    - bionic_release
    - osx_sign
    - windows_sign
