language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:63f8b74a76acbf6f40e0d646d9b4b1eb8ce09b9a732254f3ff759d193f87a1fc /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux"
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:63f8b74a76acbf6f40e0d646d9b4b1eb8ce09b9a732254f3ff759d193f87a1fc /bin/sh -c "cd /ga && ./tools/buildgreen.sh windows"
