language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:d7b34c3e9ffaadfadebdd76eec5a53a4ae9db807254783fa169004fe109f65b6 /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux"
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:d7b34c3e9ffaadfadebdd76eec5a53a4ae9db807254783fa169004fe109f65b6 /bin/sh -c "cd /ga && ./tools/buildgreen.sh windows"
