language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:bbf7be69811ac476247e609557cc372766baae6b0b6e12ba6c370b69a3ca39e6 /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux"
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:bbf7be69811ac476247e609557cc372766baae6b0b6e12ba6c370b69a3ca39e6 /bin/sh -c "cd /ga && ./tools/buildgreen.sh windows"
