language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:2bd2c2839f8e399e518f4d3680c90eb871ddb51d5c2ef1c38655fcb13cef38ad /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux"
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:2bd2c2839f8e399e518f4d3680c90eb871ddb51d5c2ef1c38655fcb13cef38ad /bin/sh -c "cd /ga && ./tools/buildgreen.sh windows"
