language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:7068812f53e7b98c45cd4f5d92744ef0f38e9a720ae3daf70f460158a7d160bf /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux"
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:7068812f53e7b98c45cd4f5d92744ef0f38e9a720ae3daf70f460158a7d160bf /bin/sh -c "cd /ga && ./tools/buildgreen.sh windows"
