language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:42cddc47f97e66cd6575931cbf4f8635ecc2cbb9fc7c1ec1468a5dcfda1198d0 /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux"
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:42cddc47f97e66cd6575931cbf4f8635ecc2cbb9fc7c1ec1468a5dcfda1198d0 /bin/sh -c "cd /ga && ./tools/buildgreen.sh windows"
