package:build:
  tags:
    - garelease
  stage: package
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/green_qt_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - rm -fr green_qt_dist
    - mkdir green_qt_dist
    - mv BlockstreamGreenSetup.exe green_qt_dist/BlockstreamGreenSetup-x86_64.exe
    - mv "macos-arm64/Blockstream Green.dmg" green_qt_dist/BlockstreamGreen-arm64.dmg
    - mv "macos-x86_64/Blockstream Green.dmg" green_qt_dist/BlockstreamGreen-x86_64.dmg
    - mv "macos-universal/Blockstream Green.dmg" green_qt_dist/BlockstreamGreen-universal.dmg
    - chmod +x green
    - tar czf green_qt_dist/BlockstreamGreen-linux-x86_64.tar.gz -C . green
    - cp BlockstreamGreen-x86_64.AppImage green_qt_dist
    - chmod +x green_qt_dist/BlockstreamGreen-x86_64.AppImage
    - cd green_qt_dist
    - /opt/process_release
    - cat SHA256SUMS.asc
  needs:
    - linux-x86_64:build-appimage
    - linux-x86_64:build-binary
    - macos-arm64:staple
    - macos-x86_64:staple
    - macos-universal:staple
    - windows-x86_64:sign-installer

.publish:
  tags:
    - ga
  stage: package
  when: manual
  needs: ["package:build"]
  image: glregistry.blockstream.io/blockstream/p/gcloud-docker:tf0.15.4
  script:
    - cd green_qt_dist
    - ../tools/publish.sh

package:publish-rc:
  extends:
    - .publish
  variables:
    CHANNEL: rc

package:publish-latest:
  extends:
    - .publish
  variables:
    CHANNEL: latest
