package:build:
  tags:
    - garelease
  stage: package
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/green_qt_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - rm -fr green_qt_dist
    - mkdir green_qt_dist
    - mv GreenSigned.exe "BlockstreamGreenSetup.exe"
    - zip -j green_qt_dist/BlockstreamGreen_Windows_x86_64.zip "BlockstreamGreenSetup.exe"
    - zip -r green_qt_dist/BlockstreamGreen_MacOS_x86_64.zip "Blockstream Green.dmg"
    - chmod +x green
    - tar czf green_qt_dist/BlockstreamGreen_Linux_x86_64.tar.gz -C . green
    - cp BlockstreamGreen-x86_64.AppImage green_qt_dist
    - chmod +x green_qt_dist/BlockstreamGreen-x86_64.AppImage
    - cd green_qt_dist
    - /opt/process_release
  needs:
    - linux-x86_64:build
    - macos-universal:staple
    - windows-x86_64:sign-installer

package:publish:
  tags:
    - ga
  stage: package
  when: manual
  needs: ["package:build"]
  image: glregistry.blockstream.io/blockstream/p/gcloud-docker:tf0.15.4
  script:
    - cd green_qt_dist
    - ../tools/publish.sh
